# Generated by Django 3.1.2 on 2020-12-27 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appelresortShop', '0003_auto_20201226_1216'),
        ('appelresortShop', '0003_auto_20201227_2035'),
    ]

    operations = [
    ]
