# Generated by Django 3.1.3 on 2020-11-24 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coleccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_introducido', models.DateField()),
                ('descripcion', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(default='')),
                ('descuento', models.CharField(choices=[('50%', 'Descuento a la mitad'), ('30%', 'Descuento del 30%'), ('20%', 'Descuento del 20%'), ('2x1', 'Paga 1 y llévate otro gratis'), ('3x2', 'Paga 2 y llévate otro gratis')], max_length=3)),
                ('is_activa', models.BooleanField(default=False)),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField(default='')),
                ('visitas', models.IntegerField(default=0)),
                ('talla', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=2)),
                ('fecha_insertado', models.DateField()),
                ('color', models.CharField(max_length=30)),
                ('imagen', models.ImageField(upload_to='')),
                ('coleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apparropame.coleccion')),
                ('etiquetas', models.ManyToManyField(to='apparropame.Etiqueta')),
                ('ofertas', models.ManyToManyField(blank=True, to='apparropame.Oferta')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('texto_comentario', models.TextField(default='')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apparropame.item')),
            ],
        ),
        migrations.AddField(
            model_name='coleccion',
            name='etiquetas',
            field=models.ManyToManyField(to='apparropame.Etiqueta'),
        ),
        migrations.AddField(
            model_name='coleccion',
            name='ofertas',
            field=models.ManyToManyField(blank=True, to='apparropame.Oferta'),
        ),
    ]
